---
# rhel_mssqlinstall

- name: Install MS SQL Server on RHEL
  hosts: '{{ survey_vm_hostname }}'
  gather_facts: no

  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_version: 2019
    mssql_password: "p@55w0rD"
    mssql_edition: Developer
  roles:
    - microsoft.sql.server