---
# site.yml for win_mssqlserver

- name: Project win_mssqlserver
  hosts: '{{ survey_vm_hostname }}'
  gather_facts: no

  vars:
    ansible_user: '{{ windowsuser }}'
    ansible_password: '{{ windowspassword }}'
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    win_dom_user: '{{ domainuser }}'
    win_dom_pw: '{{ domainpassword }}'
    db_agent_user: dbagentuser
    db_engine_user: dbengineuser
    db_pw: eP@ssw0rd!157#
    db_cpu_for_maxdop: 2
    db_sapwd: Ansible01
    inst_url: 'https://go.microsoft.com/fwlink/p/?linkid=866662'
    inst_file: 'C:\Temp\SQL2019-SSEI-Dev.exe'
    inst_db_type: SQLServer
    inst_config_file: 'C:\Temp\SQLServer.ini'
    dir_sqlbackups: 'C:\SQLBackups'
    dir_sqldata: 'C:\SQLData'
    dir_mssql: 'C:\MSSQL'
    dir_sqllogs: 'C:\SQLLogs'
    dir_tempdb: 'C:\TempDB'
    dir_temp: 'C:\Temp'
    var_db_name: DBATools
    dba_local_group: 'DBA Local Admins'
    inst_dbcreate_file: 'C:\Temp\DBCreate.sql'
    db_dirs:
      - '{{ dir_sqlbackups }}'
      - '{{ dir_sqldata }}'
      - '{{ dir_mssql }}'
      - '{{ dir_sqllogs }}'
      - '{{ dir_tempdb }}'
      - '{{ dir_temp }}'
    db_admins:
      - '{{ db_agent_user }}'
      - '{{ db_engine_user }}'
      
      
  tasks:
  - name: Setup MS SQL Server on '{{ ansible_fqdn }}'
    include_role:
      name: role_win_mssqlserver
      apply:
        tags:
          - win_mssqlserver
    tags:
      - always
