---
- hosts: 172.16.1.100
  gather_facts: false
  become: false 

  vars:
    ansible_user: '{{ windowsuser }}'
    ansible_password: '{{ windowspassword }}'
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
#    inst_file: SQL2019-SSEI-Dev.exe
#    inst_config_file: SQLServer.ini
    inst_file: 'C:\Temp\SQLINST.exe'
    inst_config_file: 'C:\Temp\SQLServerConfig.ini'
#    inst_file: 'C:\Users\sesvro01\Downloads\SQLINST.exe'
#    inst_config_file: 'C:\Users\sesvro01\Downloads\SQLServerConfig.ini'

  tasks:

  - name: Ping win server
    win_ping:

#  - name: Install git
#    win_chocolatey:
#      name: git
#      state: present

#      
#  - name: Display the output from psexec
#    debug:
#      msg: '{{ psexec_output }}'

    
#
#    - name: Run SQL Server Installer command-line
#      win_shell: "{{ inst_file }} /Q /CONFIGURATIONFILE={{ inst_config_file }} /IACCEPTSQLSERVERLICENSETERMS=True"
#      win_shell: 'C:\Temp\SQLINST.exe /Q /CONFIGURATIONFILE=C:\SQLServerConfig.ini /IACCEPTSQLSERVERLICENSETERMS=True'
#      ansible_become: yes


  - name: Create directory structure
    win_file:
      path: C:\Temp
      state: directory

#    - name: Reboot windows machine
#      win_reboot: